import os

DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN", False)


#reddit config
REDDIT_APP_ID = os.getenv("REDDIT_APP_ID", False)
REDDIT_APP_SECRET = os.getenv("REDDIT_APP_SECRET", False)
REDDIT_ENABLED_MEME_SUBREDDITS = [
    '',
    'AnimeMeme',
    'animememes',
    'AnimeMemer'
]
REDDIT_ENABLED_HENTAI_SUBREDDITS = [
    '',
    'hentai',
    'rule34',
    'Ecchi',
    'AnimeAss',
    'animeassholes',
    'animebodysuits',
    'AleatoryHentai',
    'animebikinis',
    'animehandbras',
    'AnimeHeelsAndBoots',
    'animelegs',
    'animelegwear',
    'AnimeLingerie',
    'animemaids',
    'AnimeMILFS',
    'animemilkers',
    'Animepantsu',
    'animethighss',
    'AnimeTitties',
    'Artistic_Hentai',
    'AzurLewd',
    'BigAnimeTiddies',
    'CultureImpact',
    'CumHentai',
    'cute_hentai',
    'dekaihentai',
    'Ecchibondage',
    'ElfHentai',
    'FateEcchi',
    'GenshinImpactNSFW',
    'glasshentai',
    'HardcoreHentaiBondage',
    'HENTAI_GIF',
    'HentaiBeast',
    'HentaiBlessing',
    'hentaibondage',
    'HentaiCumsluts',
    'HonkaiImpactRule34',
    'LewdAnimeGirls',
    'LoweredPantyhose',
    'lowlegsheaven',
    'MaidHentai',
    'NSFWEcchi',
    'Oppai',
    'oppai_gif',
    'OppaiLove',
    'OverOppai',
    'pantsu',
    'rape_hentai',
    'Rule34cumsluts',
    'SoakedHentai',
    'Taihou',
    'ThiccElves',
    'thick_hentai',
    'thighdeology',
    'thighhighhentai',
    'uncensoredhentai',
    'UpskirtHentai',
    'waifusgonewild',
    'WaifusOnCouch',
    'ZeroTwoBooty',
    'ZeroTwoHentai'
]
